--- # Ansible project
- hosts: demo
  user: ansible
  become: yes
  tasks: 
    - name: war file
      copy: 
      src: target/webfile-lates.war
      dest: /var/lib/tomcat9/webapps/target/webfile-lates.war
      owner: tomcat9
      group: tomcat9
